# Generated by Django 3.2.8 on 2021-10-10 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
